### ISSUE TITLE
Fantastic work! Can it go on img2img tab too?

### ISSUE THREAD

**Issue by Luke2642** [antis0007/sd-webui-multiple-hypernetworks#3] opened 2022-12-01 20:01 UTC
This works great, I'm really impressed, thanks so much!

Can it go on img2img tab too? It doesn't appear in the scripts dropdown on that tab.

**Comment by Luke2642** [comment] 2022-12-01 20:10
It seems to affect generations on the img2img tab too! Maybe add this to the readme :-)

**Comment by antis0007** [comment] 2022-12-01 20:44
Just changed a line, should be fixed now. Not sure about the undefined behaviour caused by having the script open in both tabs at once but I'll look into it.

**Comment by Luke2642** [comment] 2022-12-01 21:45
I've also encountered a couple more bugs in my own stupidity.

- If I copy a particular hypernetwork pt from an earlier point in training, say number hyp-a-250, then paste it into the models\hypernetworks folder with a new name hyp-b, it appears fine in the list on your script, but gives errror KeyError: 'hyp-b(a951b812)'. Typing hyp-a(hex) pulls up the old one fine. Restarted webui and this fixed it! So I guess it needs a blue refresh button too?

- It also seems to stop the regular drop down and strength slider on the settings tab from working too. I guess 'Reset' should fix this, oops.

**Comment by Luke2642** [comment] 2022-12-10 11:42
The latest revision of webui breaks this, index out of range on line 289 of the .py. Rolling back to an earlier commit and it works again, I did:

git checkout 9539c2045a2de9e900b96acbf67e41fafe93c6f6

**Closed as completed** 2022-12-10 11:43 UTC
